### ISSUE TITLE
Support enums as record field types?

### ISSUE THREAD

**Issue by thewildllama** [naynecoder/yorm#21]
Hey, there! Cool library!

What's your take on supporting `record`s with enum types for some of the fields? Jackson seems to be able to detect the enum and call `valueOf()`. (or something... maybe they're doing something more magical...)

```java
public class Example {
    public enum ExampleEnum {
        EXAMPLE1,
        EXAMPLE2
    }

    public record ExampleRecord(
            int id,
            String exampleString,
            int exampleInt,
            ExampleEnum exampleEnum
    ) {}
}
```

Assuming a table like this:

```sql
CREATE TABLE IF NOT EXISTS example_record (
    id INTEGER PRIMARY KEY,
    exampleString TEXT,
    exampleInt INTEGER,
    exampleEnum TEXT
);
```

Right now, it seems like the `MapBuilder` assumes the field is a `String` (which makes sense).

```
Exception in thread "main" java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:65)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.yorm.db.ReflectionUtil.buildSample(ReflectionUtil.java:40)
	at org.yorm.db.ReflectionUtil.<init>(ReflectionUtil.java:32)
	at org.yorm.YormTable.<init>(YormTable.java:25)
	at org.yorm.MapBuilder.buildMap(MapBuilder.java:58)
	at org.yorm.Yorm.getTable(Yorm.java:127)
	at org.yorm.Yorm.insert(Yorm.java:41)
	at com.example.Example.main(Example.java)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to com.example.Example$ExampleEnum
	at java.base/java.lang.Class.cast(Class.java:4090)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 9 more
```

I can take a stab at implementing it, but I figured I'd chat with you about it first! Thanks!

**Comment by naynecoder** [comment]
Hi Ryan! Perfect timing, we are using this library in production and recently a similar issue popped out. Of course, if you are already have in mind a way to fix it, contributions to the library are very much welcomed

**Comment by thewildllama** [comment]
Yeah! I'm still getting the lay of the land, but from what I've gathered so far (**WARNING** _my current level of knowledge with this code is "complete idiot", haha!_), there's at least two main changes:

  * Change the formation of `YormTuple` to include more information about the target Java type. Specifically, how to convert the DB type to the target type.
  * Change `RowRecordConverter.recordToRow()` and `RowRecordConverter.rowToRecord()`  to use the conversion information.

I love side quests! So I'll happily take a look at it. If it gets too messy, I'll let you know that I'm giving up! :)

I used Jdbi for now, but I'm not a fan of all that boiler code... I think you've got a fun little library, here! A million thanks!

**Comment by naynecoder** [comment]
Thanks to you! I'd say you are on the right track, if you have the feeling it's getting too complicated, no worries, you can share what you've tried and I'll try to incorporate, it's definitely a needed addition to the library.
Regarding avoiding boilerplate, I'm on the same page, and that's indeed one of the purposes of this library

**Comment by thewildllama** [comment]
I got something working! I posted a draft PR to get the conversation going!

I'm too dumb to figure out how to link the issue to the PR, haha!

https://github.com/naynecoder/yorm/pull/22

**Comment by naynecoder** [comment]
Well, it's been merged and published to Maven Central, version 0.0.8 will be available soon with Enums support thanks to you!
