### ISSUE TITLE
No deserializer found for java.lang.String to char

### ISSUE THREAD

**Issue by xylo04** [naynecoder/yorm#25]
```
java.lang.RuntimeException: No deserializer found for java.lang.String to char. You should file a bug to let us know what we need to add!
	at org.yorm.util.RowRecordConverter.converterFor(RowRecordConverter.java:157) ~[yorm-0.0.8.jar:na]
	at org.yorm.MapBuilder.populateMap(MapBuilder.java:124) ~[yorm-0.0.8.jar:na]
	at org.yorm.MapBuilder.buildMap(MapBuilder.java:52) ~[yorm-0.0.8.jar:na]
	at org.yorm.Yorm.getTable(Yorm.java:127) ~[yorm-0.0.8.jar:na]
	at org.yorm.Yorm.find(Yorm.java:83) ~[yorm-0.0.8.jar:na]
	at org.rmham.devdb.map.model.DataLoader.loadData(DataLoader.java:23) ~[main/:na]
	...
```

**Comment by naynecoder** [comment]
Hi @xylo04! Thanks for reporting this, I've we are getting it right, you were trying to use a char? Could you please specify the type used in the database, and the database engine? Thanks in advance!

**Comment by xylo04** [comment]
Hi! Yes, I should've included more information. The table is in MariaDB (InnoDB), and I have many columns with `char` types like `char(32)`. I'm attempting to map those to `java.lang.String`s.

The database has also evolved to have `text` columns and the occasional `varchar(255)` column so there's no consistency. I suppose we all have to work with what's in front of us, right?

**Comment by naynecoder** [comment]
Understood, thanks @xylo04, I can work with that! Indeed, dealing with inconsistencies always becomes part of the business. Anyway, I think we all have seen worse than that

**Comment by naynecoder** [comment]
Just some heads up to say we are on it. It turns out CHAR type is basically a VARCHAR with certain features, so at Java records level we can consider it always Strings. At least with Mysql. We are on the process of making sure it's working for other engines, because at least PostgreSQL it's padding the content with empty spaces

**Comment by naynecoder** [comment]
Latest version, 0.8.1, should have fixed it. It's already in Maven Central

**Comment by xylo04** [comment]
Excellent, thank you!
